version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9

    working_directory: /go/src/github.com/jamillosantos/http
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: go get -u github.com/onsi/ginkgo/ginkgo
    - run: make deps
    - run: make coverage
    - run: bash <(curl -s https://codecov.io/bash)